//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bags
    {
        public Bags()
        {
            this.Warehouse = new HashSet<Warehouse>();
        }
    
        public int Id { get; set; }
        public int Count { get; set; }
    
        public virtual ICollection<Warehouse> Warehouse { get; set; }
    }
}
