//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetState
    {
        public BudgetState()
        {
            this.Budget = new HashSet<Budget>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeOfBudgetActionID { get; set; }
        public bool Visible { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual ICollection<Budget> Budget { get; set; }
        public virtual TypeOfBudgetAction TypeOfBudgetAction { get; set; }
    }
}
