//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public int BudgetStateID { get; set; }
        public System.DateTime Date { get; set; }
        public string Note { get; set; }
    
        public virtual BudgetState BudgetState { get; set; }
    }
}
