//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.PositionInOrder = new HashSet<PositionInOrder>();
            this.PositionInSupply = new HashSet<PositionInSupply>();
            this.Warehouse = new HashSet<Warehouse>();
        }
    
        public int Id { get; set; }
        public int FoodNameID { get; set; }
        public int FoodWeightID { get; set; }
        public int GranuleID { get; set; }
        public int PriceID { get; set; }
        public bool Visible { get; set; }
    
        public virtual FoodName FoodName { get; set; }
        public virtual FoodWeight FoodWeight { get; set; }
        public virtual Granule Granule { get; set; }
        public virtual Price Price { get; set; }
        public virtual ICollection<PositionInOrder> PositionInOrder { get; set; }
        public virtual ICollection<PositionInSupply> PositionInSupply { get; set; }
        public virtual ICollection<Warehouse> Warehouse { get; set; }
    }
}
