//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDataBaseEntity : DbContext
    {
        public MainDataBaseEntity()
            : base("name=MainDataBaseEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Budget> Budget { get; set; }
        public DbSet<BudgetState> BudgetState { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<Food> Food { get; set; }
        public DbSet<FoodName> FoodName { get; set; }
        public DbSet<FoodWeight> FoodWeight { get; set; }
        public DbSet<Granule> Granule { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<PositionInOrder> PositionInOrder { get; set; }
        public DbSet<PositionInSupply> PositionInSupply { get; set; }
        public DbSet<Price> Price { get; set; }
        public DbSet<Supply> Supply { get; set; }
        public DbSet<TypeOfBudgetAction> TypeOfBudgetAction { get; set; }
        public DbSet<TypeOfDelivery> TypeOfDelivery { get; set; }
        public DbSet<TypeOfEvent> TypeOfEvent { get; set; }
        public DbSet<TypeOfSale> TypeOfSale { get; set; }
        public DbSet<Warehouse> Warehouse { get; set; }
    }
}
