//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.PositionInOrder = new HashSet<PositionInOrder>();
        }
    
        public int Id { get; set; }
        public int ClientID { get; set; }
        public int TypeOfDeliveryID { get; set; }
        public decimal CostOfDelivery { get; set; }
        public decimal Amount { get; set; }
        public bool CarriedOut { get; set; }
        public bool Paid { get; set; }
        public bool DeliveryPaid { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TypeOfDelivery TypeOfDelivery { get; set; }
        public virtual ICollection<PositionInOrder> PositionInOrder { get; set; }
    }
}
