//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionInSupply
    {
        public int Id { get; set; }
        public int SupplyID { get; set; }
        public int FoodID { get; set; }
        public int CountOfBags { get; set; }
        public bool CarriedOut { get; set; }
        public bool Paid { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
