//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public Price()
        {
            this.Food = new HashSet<Food>();
        }
    
        public int Id { get; set; }
        public decimal Retail { get; set; }
        public decimal Kennel { get; set; }
        public decimal Purchase { get; set; }
        public decimal ForSelf { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<Food> Food { get; set; }
    }
}
