//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrHrumsHomeEdition.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public Supply()
        {
            this.PositionInSupply = new HashSet<PositionInSupply>();
        }
    
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<PositionInSupply> PositionInSupply { get; set; }
    }
}
